global:
  scrape_interval: 2m
  scrape_timeout: 10s
  evaluation_interval: 2m

  external_labels:
    monitor: 'codelab-monitor'
  query_log_file: PromQL_log.log

rule_files:
  - "rule.yml"

scrape_configs:
  - job_name: 'scrape_metric'
    scheme: 'https'
    metrics_path: '/actuator/prometheus'
    authorization:
      type: 'Bearer'
      credentials_file: Jwt.txt
    
    static_configs:
      - targets: ['server.gauth.co.kr']