global:
  scrape_interval: 2m
  scrape_timeout: 10s
  evaluation_interval: 

  external_labels:
    monitor: 'codelab-monitor'
  query_log_file: PromQL_log.log

rule_files:
  - "rule.yml"

scrape_configs:
  - job_name: 'scrape_metric'
    schema: 'http'
    authorization:
      type: 'Bearer'
      credentials_file: Jwt.txt
    scrape_interval:
    
static_configs:
  - targets: ['localhost:9090', 'localhost:8080']
    labels:
      service: 'scrape-data'
  